// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs0jhCD6FMlavGfDeSntDz1f2UZRk2bmI',
    appId: '1:470765122991:web:fc4d01eda0926931d2ab5a',
    messagingSenderId: '470765122991',
    projectId: 'fitnesss-99',
    authDomain: 'fitnesss-99.firebaseapp.com',
    storageBucket: 'fitnesss-99.firebasestorage.app',
    measurementId: 'G-6MW0ZMJV70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtv95P85GwllDM7bAsuvb90ztoP_XDF60',
    appId: '1:470765122991:android:d6e7752630d72ff7d2ab5a',
    messagingSenderId: '470765122991',
    projectId: 'fitnesss-99',
    storageBucket: 'fitnesss-99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9p0CUrxMzEUWztAUK9jXMQuF4kl0npRk',
    appId: '1:470765122991:ios:3605c82059dd4dddd2ab5a',
    messagingSenderId: '470765122991',
    projectId: 'fitnesss-99',
    storageBucket: 'fitnesss-99.firebasestorage.app',
    iosBundleId: 'com.example.fitnessDietPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9p0CUrxMzEUWztAUK9jXMQuF4kl0npRk',
    appId: '1:470765122991:ios:3605c82059dd4dddd2ab5a',
    messagingSenderId: '470765122991',
    projectId: 'fitnesss-99',
    storageBucket: 'fitnesss-99.firebasestorage.app',
    iosBundleId: 'com.example.fitnessDietPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs0jhCD6FMlavGfDeSntDz1f2UZRk2bmI',
    appId: '1:470765122991:web:8a0b79cce82f4454d2ab5a',
    messagingSenderId: '470765122991',
    projectId: 'fitnesss-99',
    authDomain: 'fitnesss-99.firebaseapp.com',
    storageBucket: 'fitnesss-99.firebasestorage.app',
    measurementId: 'G-ZQ4T7KHR41',
  );
}
